title: Deliang Wei's Homepage
page-top-title: Deliang Wei
top-section-bg-text: Computational Imaging · Optimization · Generative AI
home-subtitle: Postdoctoral Researcher | Johns Hopkins University
copyright-text: '© Deliang Wei 2026. All Rights Reserved.'
